// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxqzqwmqesbvwbuafbuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cXpxd21xZXNidndidWFmYnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODE4NzEsImV4cCI6MjA3NDI1Nzg3MX0.mgZ2LIVJaMjRfeBMX2C9F5acZivxlViLzZseC6zGxBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});